// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveProject(arg1) {
  return window['go']['main']['App']['ArchiveProject'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListArchivedProjects() {
  return window['go']['main']['App']['ListArchivedProjects']();
}

export function ListArchivedTasksByProject(arg1) {
  return window['go']['main']['App']['ListArchivedTasksByProject'](arg1);
}

export function ListDoneTasksByProject(arg1) {
  return window['go']['main']['App']['ListDoneTasksByProject'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListTasksByProject(arg1) {
  return window['go']['main']['App']['ListTasksByProject'](arg1);
}

export function SetCurrentTask(arg1) {
  return window['go']['main']['App']['SetCurrentTask'](arg1);
}

export function SetTaskStatus(arg1, arg2) {
  return window['go']['main']['App']['SetTaskStatus'](arg1, arg2);
}

export function SetTrackingPaused(arg1) {
  return window['go']['main']['App']['SetTrackingPaused'](arg1);
}

export function UnarchiveProject(arg1) {
  return window['go']['main']['App']['UnarchiveProject'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}
