// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveProject(arg1) {
  return window['go']['main']['App']['ArchiveProject'](arg1);
}

export function CreateAssignmentRule(arg1) {
  return window['go']['main']['App']['CreateAssignmentRule'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteAssignmentRule(arg1) {
  return window['go']['main']['App']['DeleteAssignmentRule'](arg1);
}

export function GetAppIcon(arg1) {
  return window['go']['main']['App']['GetAppIcon'](arg1);
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetDBPath() {
  return window['go']['main']['App']['GetDBPath']();
}

export function GetIdleDetectorTier() {
  return window['go']['main']['App']['GetIdleDetectorTier']();
}

export function GetThemeCSS() {
  return window['go']['main']['App']['GetThemeCSS']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListActivityBlocksForRange(arg1, arg2) {
  return window['go']['main']['App']['ListActivityBlocksForRange'](arg1, arg2);
}

export function ListArchivedProjects() {
  return window['go']['main']['App']['ListArchivedProjects']();
}

export function ListArchivedTasksByProject(arg1) {
  return window['go']['main']['App']['ListArchivedTasksByProject'](arg1);
}

export function ListAssignmentRules() {
  return window['go']['main']['App']['ListAssignmentRules']();
}

export function ListDoneTasksByProject(arg1) {
  return window['go']['main']['App']['ListDoneTasksByProject'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListTasksByProject(arg1) {
  return window['go']['main']['App']['ListTasksByProject'](arg1);
}

export function OpenDataFolder() {
  return window['go']['main']['App']['OpenDataFolder']();
}

export function PickAvatar() {
  return window['go']['main']['App']['PickAvatar']();
}

export function SetAFKThreshold(arg1) {
  return window['go']['main']['App']['SetAFKThreshold'](arg1);
}

export function SetCurrentTask(arg1) {
  return window['go']['main']['App']['SetCurrentTask'](arg1);
}

export function SetTaskStatus(arg1, arg2) {
  return window['go']['main']['App']['SetTaskStatus'](arg1, arg2);
}

export function SetTrackingPaused(arg1) {
  return window['go']['main']['App']['SetTrackingPaused'](arg1);
}

export function SplitActivityBlock(arg1, arg2) {
  return window['go']['main']['App']['SplitActivityBlock'](arg1, arg2);
}

export function UnarchiveProject(arg1) {
  return window['go']['main']['App']['UnarchiveProject'](arg1);
}

export function UpdateActivityBlockAssignment(arg1, arg2) {
  return window['go']['main']['App']['UpdateActivityBlockAssignment'](arg1, arg2);
}

export function UpdateAssignmentRule(arg1) {
  return window['go']['main']['App']['UpdateAssignmentRule'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}
