// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tracker} from '../models';

export function ArchiveProject(arg1:number):Promise<void>;

export function CreateProject(arg1:tracker.Project):Promise<number>;

export function CreateTask(arg1:tracker.Task):Promise<number>;

export function GetAppState():Promise<tracker.AppState>;

export function Greet(arg1:string):Promise<string>;

export function ListArchivedProjects():Promise<Array<tracker.Project>>;

export function ListArchivedTasksByProject(arg1:number):Promise<Array<tracker.Task>>;

export function ListDoneTasksByProject(arg1:number):Promise<Array<tracker.Task>>;

export function ListProjects():Promise<Array<tracker.Project>>;

export function ListTasksByProject(arg1:number):Promise<Array<tracker.Task>>;

export function SetCurrentTask(arg1:any):Promise<void>;

export function SetTaskStatus(arg1:number,arg2:string):Promise<void>;

export function SetTrackingPaused(arg1:boolean):Promise<void>;

export function UnarchiveProject(arg1:number):Promise<void>;

export function UpdateProject(arg1:tracker.Project):Promise<void>;

export function UpdateTask(arg1:tracker.Task):Promise<void>;
