// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tracker} from '../models';
import {time} from '../models';

export function ArchiveProject(arg1:number):Promise<void>;

export function CreateAssignmentRule(arg1:tracker.Rule):Promise<number>;

export function CreateProject(arg1:tracker.Project):Promise<number>;

export function CreateTask(arg1:tracker.Task):Promise<number>;

export function DeleteAssignmentRule(arg1:number):Promise<void>;

export function GetAppIcon(arg1:string):Promise<string>;

export function GetAppState():Promise<tracker.AppState>;

export function GetAppVersion():Promise<string>;

export function GetDBPath():Promise<string>;

export function GetIdleDetectorTier():Promise<string>;

export function GetRecentLogs(arg1:number):Promise<string>;

export function GetThemeCSS():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListActivityBlocksForRange(arg1:time.Time,arg2:time.Time):Promise<Array<tracker.Block>>;

export function ListArchivedProjects():Promise<Array<tracker.Project>>;

export function ListArchivedTasksByProject(arg1:number):Promise<Array<tracker.Task>>;

export function ListAssignmentRules():Promise<Array<tracker.Rule>>;

export function ListDoneTasksByProject(arg1:number):Promise<Array<tracker.Task>>;

export function ListProjects():Promise<Array<tracker.Project>>;

export function ListTasksByProject(arg1:number):Promise<Array<tracker.Task>>;

export function OpenDataFolder():Promise<void>;

export function PickAvatar():Promise<string>;

export function SetAFKThreshold(arg1:number):Promise<void>;

export function SetCurrentTask(arg1:any):Promise<void>;

export function SetTaskStatus(arg1:number,arg2:string):Promise<void>;

export function SetTrackingPaused(arg1:boolean):Promise<void>;

export function SplitActivityBlock(arg1:number,arg2:time.Time):Promise<number>;

export function UnarchiveProject(arg1:number):Promise<void>;

export function UpdateActivityBlockAssignment(arg1:number,arg2:any):Promise<void>;

export function UpdateActivityBlockProjectOnly(arg1:number,arg2:number):Promise<void>;

export function UpdateAssignmentRule(arg1:tracker.Rule):Promise<void>;

export function UpdateProject(arg1:tracker.Project):Promise<void>;

export function UpdateTask(arg1:tracker.Task):Promise<void>;
